version: "3.8"

services:
  app:
    build: .
    container_name: unbforum-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15-alpine
    container_name: unbforum-db
    ports:
      - "5432:5432"
    volumes:
      - /var/cache/unbforum_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=unbforum

  pgadmin:
    image: dpage/pgadmin4
    container_name: unbforum-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@unbforum.com
      - PGADMIN_DEFAULT_PASSWORD=admin
