version: "3.8"

services:
  app-test:
    build: .
    container_name: unbforum-api-test
    depends_on:
      - db-test
    volumes:
      - .:/app
    environment:
      - DB_URL=postgresql+psycopg2://test:pass@db-test/unbforum_test
      - SECRET_KEY=ae41b99a04f6082a403515dd33aa43ec69e0603be5c412448d4acdd38143d457
      - ALGORITHM=HS256
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  db-test:
    image: postgres:15-alpine
    container_name: unbforum-db-test
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=unbforum_test
