"""upgrade foreign key constraints

Revision ID: 5c9c06154bc2
Revises: 98057ab44a65
Create Date: 2023-11-18 18:12:59.940075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c9c06154bc2'
down_revision: Union[str, None] = '98057ab44a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('topic_has_category_category_id_fkey', 'topic_has_category', type_='foreignkey')
    op.drop_constraint('topic_has_category_topic_id_fkey', 'topic_has_category', type_='foreignkey')
    op.create_foreign_key(None, 'topic_has_category', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'topic_has_category', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_has_tag_tag_id_fkey', 'user_has_tag', type_='foreignkey')
    op.drop_constraint('user_has_tag_user_id_fkey', 'user_has_tag', type_='foreignkey')
    op.create_foreign_key(None, 'user_has_tag', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_has_tag', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_has_tag', 'updated_at')
    op.drop_column('user_has_tag', 'created_at')
    op.drop_constraint('user_rates_topic_topic_id_fkey', 'user_rates_topic', type_='foreignkey')
    op.drop_constraint('user_rates_topic_user_id_fkey', 'user_rates_topic', type_='foreignkey')
    op.create_foreign_key(None, 'user_rates_topic', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_rates_topic', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_saves_topic_user_id_fkey', 'user_saves_topic', type_='foreignkey')
    op.drop_constraint('user_saves_topic_topic_id_fkey', 'user_saves_topic', type_='foreignkey')
    op.create_foreign_key(None, 'user_saves_topic', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_saves_topic', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_saves_topic', type_='foreignkey')
    op.drop_constraint(None, 'user_saves_topic', type_='foreignkey')
    op.create_foreign_key('user_saves_topic_topic_id_fkey', 'user_saves_topic', 'topics', ['topic_id'], ['id'])
    op.create_foreign_key('user_saves_topic_user_id_fkey', 'user_saves_topic', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_rates_topic', type_='foreignkey')
    op.drop_constraint(None, 'user_rates_topic', type_='foreignkey')
    op.create_foreign_key('user_rates_topic_user_id_fkey', 'user_rates_topic', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_rates_topic_topic_id_fkey', 'user_rates_topic', 'topics', ['topic_id'], ['id'])
    op.add_column('user_has_tag', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('user_has_tag', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_has_tag', type_='foreignkey')
    op.drop_constraint(None, 'user_has_tag', type_='foreignkey')
    op.create_foreign_key('user_has_tag_user_id_fkey', 'user_has_tag', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_has_tag_tag_id_fkey', 'user_has_tag', 'tags', ['tag_id'], ['id'])
    op.drop_constraint(None, 'topic_has_category', type_='foreignkey')
    op.drop_constraint(None, 'topic_has_category', type_='foreignkey')
    op.create_foreign_key('topic_has_category_topic_id_fkey', 'topic_has_category', 'topics', ['topic_id'], ['id'])
    op.create_foreign_key('topic_has_category_category_id_fkey', 'topic_has_category', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
