"""update migrations

Revision ID: b7cffdc02838
Revises: 5c9c06154bc2
Create Date: 2023-11-25 09:50:48.873386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7cffdc02838'
down_revision: Union[str, None] = '5c9c06154bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('name', sa.String(), nullable=False))
    op.add_column('files', sa.Column('content_type', sa.String(), nullable=False))
    op.add_column('files', sa.Column('upload_path', sa.String(), nullable=False))
    op.alter_column('files', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('files', 'comment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('files', 'path')
    op.add_column('topic_has_category', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('topic_has_category', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_has_tag', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_has_tag', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_rates_topic', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_rates_topic', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_saves_topic', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_saves_topic', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_saves_topic', 'updated_at')
    op.drop_column('user_saves_topic', 'created_at')
    op.drop_column('user_rates_topic', 'updated_at')
    op.drop_column('user_rates_topic', 'created_at')
    op.drop_column('user_has_tag', 'updated_at')
    op.drop_column('user_has_tag', 'created_at')
    op.drop_column('topic_has_category', 'updated_at')
    op.drop_column('topic_has_category', 'created_at')
    op.add_column('files', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('files', 'comment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('files', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('files', 'upload_path')
    op.drop_column('files', 'content_type')
    op.drop_column('files', 'name')
    # ### end Alembic commands ###
