"""update user constraint on topic and category tables

Revision ID: cdaa48357a15
Revises: db7c4fb4eeba
Create Date: 2023-12-14 22:08:34.710782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdaa48357a15'
down_revision: Union[str, None] = 'db7c4fb4eeba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('topics', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('topics_user_id_fkey', 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key('topics_user_id_fkey', 'topics', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('topics', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
